#!/usr/bin/env node
/**
 * Build the Flutter fixture app for a target platform.
 *
 * Mobile diverges from the desktop archetypes: there's no Rust/binary the service launches — Appium
 * installs and launches a *native app artifact* (an Android debug APK or an iOS simulator `.app`).
 * The native platform projects are generated by `flutter create`, so (mirroring upstream) only the
 * Dart source (`app/lib/main.dart`) + `app/pubspec.yaml` are committed. This script scaffolds a fresh
 * Flutter project into the gitignored `.flutter-build/`, overlays the committed source, and builds the
 * **debug** artifact.
 *
 * Debug is mandatory once the (deferred) execute/mock specs are re-enabled — the Dart VM Service they
 * attach to is only exposed by debug/profile builds. Find/tap (the runnable subset) works regardless,
 * but we build debug throughout for parity with what the specs will need.
 *
 * Usage:  node ./scripts/build-app.mjs [android|ios]
 *   - Platform also reads from FLUTTER_PLATFORM (arg wins); defaults to android.
 *   - FLUTTER_APP_PATH set (CI) → no-op: CI builds the artifact in a dedicated workflow step and
 *     points the WDIO config straight at it, so this stays a cheap, idempotent `turbo build` dep.
 */
import { execFileSync } from 'node:child_process';
import { cpSync, existsSync, globSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const appSrc = join(root, 'app');
const buildDir = join(root, '.flutter-build');

const platform = (process.argv[2] ?? process.env.FLUTTER_PLATFORM ?? 'android').toLowerCase();
if (platform !== 'android' && platform !== 'ios') {
  console.error(`Unsupported platform '${platform}'. Use 'android' or 'ios'.`);
  process.exit(1);
}

// app/pubspec.yaml is the single source of truth for the Dart package name — `flutter create`'s
// --project-name must match the overlaid pubspec, or `flutter pub get` complains.
const pubspec = readFileSync(join(appSrc, 'pubspec.yaml'), 'utf-8');
const projectName = pubspec.match(/^name:\s*(\S+)/m)?.[1] ?? 'wdio_flutter_fixture';

const artifactGlob =
  platform === 'ios'
    ? join(buildDir, 'build', 'ios', 'iphonesimulator', '*.app')
    : join(buildDir, 'build', 'app', 'outputs', 'flutter-apk', 'app-debug.apk');

const run = (cmd, args, cwd = root) => {
  console.log(`\n$ ${cmd} ${args.join(' ')}  (cwd: ${cwd})`);
  execFileSync(cmd, args, { cwd, stdio: 'inherit' });
};

// CI builds the artifact itself and exports FLUTTER_APP_PATH; nothing to do here.
if (process.env.FLUTTER_APP_PATH) {
  console.log(`FLUTTER_APP_PATH is set (${process.env.FLUTTER_APP_PATH}); skipping local build.`);
  process.exit(0);
}

// Idempotent for `turbo build`: if the artifact already exists, don't rebuild.
if (globSync(artifactGlob).length > 0) {
  console.log(`Artifact already present for ${platform}: ${globSync(artifactGlob)[0]}`);
  process.exit(0);
}

// 1. Scaffold the native project (skip if a prior scaffold is present — `pnpm clean` to redo).
// Both platforms are scaffolded so either can be built from one scaffold (Android files on a mac /
// iOS files on Linux are harmless and unbuilt).
if (!existsSync(join(buildDir, 'pubspec.yaml'))) {
  console.log(`Scaffolding Flutter project into .flutter-build/ …`);
  mkdirSync(buildDir, { recursive: true });
  run('flutter', ['create', '--org', 'com.wdio', '--project-name', projectName, '--platforms=android,ios', buildDir]);
}

// 2. Overlay the committed fixture source onto the scaffold (app/ is the source of truth; flutter
// create writes its own lib/main.dart + pubspec.yaml which we replace).
cpSync(join(appSrc, 'lib', 'main.dart'), join(buildDir, 'lib', 'main.dart'));
cpSync(join(appSrc, 'pubspec.yaml'), join(buildDir, 'pubspec.yaml'));

// 3. (Android) Strip `ndkVersion` from the generated Gradle files. The fixture has no native (C/C++)
// code, so it doesn't need the NDK — but `flutter create` writes `ndkVersion = flutter.ndkVersion`,
// which makes Gradle auto-download the NDK (~1GB) at build time (a flaky fetch). Remove the line.
if (platform === 'android') {
  for (const gradle of globSync(join(buildDir, 'android', '**', 'build.gradle*'))) {
    const stripped = readFileSync(gradle, 'utf-8')
      .split('\n')
      .filter((line) => !line.includes('ndkVersion'))
      .join('\n');
    writeFileSync(gradle, stripped);
  }
}

// 4. Resolve dependencies + build the debug artifact.
run('flutter', ['pub', 'get'], buildDir);
if (platform === 'android') {
  run('flutter', ['build', 'apk', '--debug'], buildDir);
} else {
  run('flutter', ['build', 'ios', '--debug', '--simulator', '--no-codesign'], buildDir);
}

const built = globSync(artifactGlob);
if (built.length === 0) {
  console.error(`Build finished but no artifact matched ${artifactGlob}`);
  process.exit(1);
}
console.log(`\n✅ Built ${platform} artifact: ${built[0]}`);
